name: html-css-validator

on: 
  push:
    branches:
      - main

jobs:
  HTML-CSS-validation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: HTML validation
      run: |
        > VALIDATION_RESULTS.log
        echo $(curl -H "Content-Type: text/html; charset=utf-8" --data-binary "@index.php" https://validator.w3.org/nu/?out=gnu) >> VALIDATION_RESULTS.log
        cat VALIDATION_RESULTS.log
        
    - name: CSS validation
      run: |
        cd ./assets/css
        echo -e "\n\nCSS" >> ../../VALIDATION_RESULTS.log
        find ./ -name '*.css' -print0 | xargs --null -I file_name echo $(curl -H "Content-Type: text/css; charset=utf-8" --data-binary "@file_name" https://jigsaw.w3.org/css-validator/validator?output=text%2fplain&uri=) >> ../../VALIDATION_RESULTS.log
        cd ../../

    - uses: actions/upload-artifact@v3
      with:
        name: VALIDATION_RESULTS
        path: VALIDATION_RESULTS.log
