name: html-css-validator

on: 
  push:
    branches:
      - main

jobs:
  HTML-validation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: HTML validation
      run: |
        curl -H "Content-Type: text/html; charset=utf-8" \ --data-binary @FILE.html \ https://validator.w3.org/nu/?out=gnu

  CSS-validation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: CSS validation
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: assets/css
        format: text
        css: true
        
    - name: upload validation results
      uses: actions/upload-artifact@v3
      with:
        name: CSSvalidationResult
        path: CSSvalidationResult.log
