name: html-css-validator

on: 
  push:
    branches:
      - main

jobs:
  HTML-validation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: HTML validation
      run: |
        echo $(curl -H "Content-Type: text/html; charset=utf-8" --data-binary "@index.php" https://validator.w3.org/nu/?out=gnu) >> README.md

  CSS-validation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: CSS validation
      run: |
        cd ./assets/css
        ls
        find ./ -name "*.css" -print0 | xargs -o -I file_name echo "WOW_NAPOLI: file_name"
        find ./ -name '*.css' -print0 | xargs -I file_name curl -H "Content-Type: text/css; charset=utf-8" --data-binary "@file_name" https://jigsaw.w3.org/css-validator/validator?uri= >> ../../README.md
